export type City = { name: string; country: string };

function seededShuffle<T>(array: T[], seed: number): T[] {
  const result = [...array];
  let s = seed;
  for (let i = result.length - 1; i > 0; i--) {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    const j = s % (i + 1);
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

export function getDailyCities(count = 24): City[] {
  const today = new Date();
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate();
  const shuffled = seededShuffle(SITEMAP_CITIES, seed);
  return shuffled.slice(0, count);
}

export const SITEMAP_CITIES: City[] = [
  // Europe
  { name: "Paris", country: "FR" },
  { name: "Nice", country: "FR" },
  { name: "Lyon", country: "FR" },
  { name: "Marseille", country: "FR" },
  { name: "Bordeaux", country: "FR" },
  { name: "Cannes", country: "FR" },
  { name: "Monaco", country: "MC" },
  { name: "London", country: "GB" },
  { name: "Edinburgh", country: "GB" },
  { name: "Manchester", country: "GB" },
  { name: "Liverpool", country: "GB" },
  { name: "Glasgow", country: "GB" },
  { name: "Bath", country: "GB" },
  { name: "Oxford", country: "GB" },
  { name: "Cambridge", country: "GB" },
  { name: "Barcelona", country: "ES" },
  { name: "Madrid", country: "ES" },
  { name: "Seville", country: "ES" },
  { name: "Valencia", country: "ES" },
  { name: "Malaga", country: "ES" },
  { name: "Granada", country: "ES" },
  { name: "Bilbao", country: "ES" },
  { name: "San Sebastian", country: "ES" },
  { name: "Ibiza", country: "ES" },
  { name: "Palma de Mallorca", country: "ES" },
  { name: "Rome", country: "IT" },
  { name: "Milan", country: "IT" },
  { name: "Florence", country: "IT" },
  { name: "Venice", country: "IT" },
  { name: "Naples", country: "IT" },
  { name: "Amalfi", country: "IT" },
  { name: "Sorrento", country: "IT" },
  { name: "Pisa", country: "IT" },
  { name: "Siena", country: "IT" },
  { name: "Bologna", country: "IT" },
  { name: "Verona", country: "IT" },
  { name: "Turin", country: "IT" },
  { name: "Munich", country: "DE" },
  { name: "Berlin", country: "DE" },
  { name: "Frankfurt", country: "DE" },
  { name: "Hamburg", country: "DE" },
  { name: "Cologne", country: "DE" },
  { name: "Dusseldorf", country: "DE" },
  { name: "Dresden", country: "DE" },
  { name: "Heidelberg", country: "DE" },
  { name: "Lisbon", country: "PT" },
  { name: "Porto", country: "PT" },
  { name: "Faro", country: "PT" },
  { name: "Prague", country: "CZ" },
  { name: "Brno", country: "CZ" },
  { name: "Amsterdam", country: "NL" },
  { name: "Rotterdam", country: "NL" },
  { name: "The Hague", country: "NL" },
  { name: "Vienna", country: "AT" },
  { name: "Salzburg", country: "AT" },
  { name: "Innsbruck", country: "AT" },
  { name: "Brussels", country: "BE" },
  { name: "Bruges", country: "BE" },
  { name: "Ghent", country: "BE" },
  { name: "Antwerp", country: "BE" },
  { name: "Zurich", country: "CH" },
  { name: "Geneva", country: "CH" },
  { name: "Lucerne", country: "CH" },
  { name: "Interlaken", country: "CH" },
  { name: "Dublin", country: "IE" },
  { name: "Galway", country: "IE" },
  { name: "Cork", country: "IE" },
  { name: "Copenhagen", country: "DK" },
  { name: "Stockholm", country: "SE" },
  { name: "Gothenburg", country: "SE" },
  { name: "Oslo", country: "NO" },
  { name: "Bergen", country: "NO" },
  { name: "Helsinki", country: "FI" },
  { name: "Warsaw", country: "PL" },
  { name: "Krakow", country: "PL" },
  { name: "Gdansk", country: "PL" },
  { name: "Budapest", country: "HU" },
  { name: "Athens", country: "GR" },
  { name: "Santorini", country: "GR" },
  { name: "Mykonos", country: "GR" },
  { name: "Rhodes", country: "GR" },
  { name: "Istanbul", country: "TR" },
  { name: "Antalya", country: "TR" },
  { name: "Bodrum", country: "TR" },
  { name: "Reykjavik", country: "IS" },
  { name: "Dubrovnik", country: "HR" },
  { name: "Split", country: "HR" },
  { name: "Zagreb", country: "HR" },
  { name: "Ljubljana", country: "SI" },
  { name: "Tallinn", country: "EE" },
  { name: "Riga", country: "LV" },
  { name: "Vilnius", country: "LT" },
  { name: "Bucharest", country: "RO" },
  { name: "Sofia", country: "BG" },
  { name: "Valletta", country: "MT" },

  // North America
  { name: "New York City", country: "US" },
  { name: "Los Angeles", country: "US" },
  { name: "San Francisco", country: "US" },
  { name: "Chicago", country: "US" },
  { name: "Miami", country: "US" },
  { name: "Las Vegas", country: "US" },
  { name: "Seattle", country: "US" },
  { name: "Boston", country: "US" },
  { name: "Washington DC", country: "US" },
  { name: "San Diego", country: "US" },
  { name: "Denver", country: "US" },
  { name: "Austin", country: "US" },
  { name: "Nashville", country: "US" },
  { name: "New Orleans", country: "US" },
  { name: "Philadelphia", country: "US" },
  { name: "Phoenix", country: "US" },
  { name: "Portland", country: "US" },
  { name: "Honolulu", country: "US" },
  { name: "Orlando", country: "US" },
  { name: "Atlanta", country: "US" },
  { name: "Dallas", country: "US" },
  { name: "Houston", country: "US" },
  { name: "San Antonio", country: "US" },
  { name: "Santa Fe", country: "US" },
  { name: "Savannah", country: "US" },
  { name: "Charleston", country: "US" },
  { name: "Salt Lake City", country: "US" },
  { name: "Minneapolis", country: "US" },
  { name: "Toronto", country: "CA" },
  { name: "Vancouver", country: "CA" },
  { name: "Montreal", country: "CA" },
  { name: "Calgary", country: "CA" },
  { name: "Ottawa", country: "CA" },
  { name: "Quebec City", country: "CA" },
  { name: "Victoria", country: "CA" },
  { name: "Halifax", country: "CA" },
  { name: "Mexico City", country: "MX" },
  { name: "Cancun", country: "MX" },
  { name: "Guadalajara", country: "MX" },
  { name: "Puerto Vallarta", country: "MX" },
  { name: "Playa del Carmen", country: "MX" },
  { name: "Cabo San Lucas", country: "MX" },
  { name: "Oaxaca", country: "MX" },
  { name: "Merida", country: "MX" },

  // Caribbean
  { name: "Nassau", country: "BS" },
  { name: "Montego Bay", country: "JM" },
  { name: "Kingston", country: "JM" },
  { name: "Punta Cana", country: "DO" },
  { name: "Santo Domingo", country: "DO" },
  { name: "San Juan", country: "PR" },
  { name: "Havana", country: "CU" },
  { name: "Bridgetown", country: "BB" },
  { name: "George Town", country: "KY" },

  // South America
  { name: "Sao Paulo", country: "BR" },
  { name: "Rio de Janeiro", country: "BR" },
  { name: "Salvador", country: "BR" },
  { name: "Brasilia", country: "BR" },
  { name: "Florianopolis", country: "BR" },
  { name: "Buenos Aires", country: "AR" },
  { name: "Mendoza", country: "AR" },
  { name: "Cordoba", country: "AR" },
  { name: "Lima", country: "PE" },
  { name: "Cusco", country: "PE" },
  { name: "Bogota", country: "CO" },
  { name: "Medellin", country: "CO" },
  { name: "Cartagena", country: "CO" },
  { name: "Cali", country: "CO" },
  { name: "Santiago", country: "CL" },
  { name: "Valparaiso", country: "CL" },
  { name: "Montevideo", country: "UY" },
  { name: "Quito", country: "EC" },
  { name: "Guayaquil", country: "EC" },
  { name: "La Paz", country: "BO" },
  { name: "Asuncion", country: "PY" },
  { name: "Caracas", country: "VE" },

  // Asia
  { name: "Tokyo", country: "JP" },
  { name: "Kyoto", country: "JP" },
  { name: "Osaka", country: "JP" },
  { name: "Hiroshima", country: "JP" },
  { name: "Nara", country: "JP" },
  { name: "Yokohama", country: "JP" },
  { name: "Nagoya", country: "JP" },
  { name: "Fukuoka", country: "JP" },
  { name: "Sapporo", country: "JP" },
  { name: "Seoul", country: "KR" },
  { name: "Busan", country: "KR" },
  { name: "Singapore", country: "SG" },
  { name: "Bangkok", country: "TH" },
  { name: "Phuket", country: "TH" },
  { name: "Chiang Mai", country: "TH" },
  { name: "Krabi", country: "TH" },
  { name: "Pattaya", country: "TH" },
  { name: "Hong Kong", country: "HK" },
  { name: "Macau", country: "MO" },
  { name: "Taipei", country: "TW" },
  { name: "Kaohsiung", country: "TW" },
  { name: "Shanghai", country: "CN" },
  { name: "Beijing", country: "CN" },
  { name: "Xian", country: "CN" },
  { name: "Guangzhou", country: "CN" },
  { name: "Shenzhen", country: "CN" },
  { name: "Chengdu", country: "CN" },
  { name: "Hangzhou", country: "CN" },
  { name: "Mumbai", country: "IN" },
  { name: "Delhi", country: "IN" },
  { name: "Bangalore", country: "IN" },
  { name: "Jaipur", country: "IN" },
  { name: "Goa", country: "IN" },
  { name: "Agra", country: "IN" },
  { name: "Udaipur", country: "IN" },
  { name: "Kolkata", country: "IN" },
  { name: "Chennai", country: "IN" },
  { name: "Hyderabad", country: "IN" },
  { name: "Kuala Lumpur", country: "MY" },
  { name: "Penang", country: "MY" },
  { name: "Ho Chi Minh City", country: "VN" },
  { name: "Hanoi", country: "VN" },
  { name: "Da Nang", country: "VN" },
  { name: "Bali", country: "ID" },
  { name: "Jakarta", country: "ID" },
  { name: "Yogyakarta", country: "ID" },
  { name: "Manila", country: "PH" },
  { name: "Cebu", country: "PH" },
  { name: "Phnom Penh", country: "KH" },
  { name: "Siem Reap", country: "KH" },
  { name: "Kathmandu", country: "NP" },
  { name: "Colombo", country: "LK" },
  { name: "Male", country: "MV" },
  { name: "Vientiane", country: "LA" },
  { name: "Yangon", country: "MM" },

  // Middle East
  { name: "Dubai", country: "AE" },
  { name: "Abu Dhabi", country: "AE" },
  { name: "Doha", country: "QA" },
  { name: "Tel Aviv", country: "IL" },
  { name: "Jerusalem", country: "IL" },
  { name: "Amman", country: "JO" },
  { name: "Muscat", country: "OM" },
  { name: "Riyadh", country: "SA" },
  { name: "Jeddah", country: "SA" },
  { name: "Manama", country: "BH" },
  { name: "Kuwait City", country: "KW" },

  // Africa
  { name: "Cairo", country: "EG" },
  { name: "Luxor", country: "EG" },
  { name: "Alexandria", country: "EG" },
  { name: "Sharm El Sheikh", country: "EG" },
  { name: "Cape Town", country: "ZA" },
  { name: "Johannesburg", country: "ZA" },
  { name: "Durban", country: "ZA" },
  { name: "Pretoria", country: "ZA" },
  { name: "Nairobi", country: "KE" },
  { name: "Mombasa", country: "KE" },
  { name: "Marrakech", country: "MA" },
  { name: "Casablanca", country: "MA" },
  { name: "Fes", country: "MA" },
  { name: "Tangier", country: "MA" },
  { name: "Lagos", country: "NG" },
  { name: "Accra", country: "GH" },
  { name: "Zanzibar City", country: "TZ" },
  { name: "Dar es Salaam", country: "TZ" },
  { name: "Addis Ababa", country: "ET" },
  { name: "Tunis", country: "TN" },
  { name: "Dakar", country: "SN" },

  // Oceania
  { name: "Sydney", country: "AU" },
  { name: "Melbourne", country: "AU" },
  { name: "Brisbane", country: "AU" },
  { name: "Perth", country: "AU" },
  { name: "Gold Coast", country: "AU" },
  { name: "Cairns", country: "AU" },
  { name: "Adelaide", country: "AU" },
  { name: "Hobart", country: "AU" },
  { name: "Darwin", country: "AU" },
  { name: "Auckland", country: "NZ" },
  { name: "Wellington", country: "NZ" },
  { name: "Queenstown", country: "NZ" },
  { name: "Christchurch", country: "NZ" },
  { name: "Rotorua", country: "NZ" },
  { name: "Suva", country: "FJ" },
  { name: "Nadi", country: "FJ" },
  { name: "Papeete", country: "PF" },
];

